-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.


CREATE TABLE IF NOT EXISTS public.certificado_digital
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    certificado bytea NOT NULL,
    propietario character varying(20) COLLATE pg_catalog."default",
    contrasena text COLLATE pg_catalog."default",
    fecha_caducidad date,
    fecha_actualizacion date DEFAULT CURRENT_DATE,
    CONSTRAINT certificado_digital_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.clientes
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    nombre text COLLATE pg_catalog."default" NOT NULL,
    apellido text COLLATE pg_catalog."default" NOT NULL,
    cedula text COLLATE pg_catalog."default" NOT NULL,
    nro_tel_princ text COLLATE pg_catalog."default" NOT NULL,
    email text COLLATE pg_catalog."default",
    ruc text COLLATE pg_catalog."default",
    direccion text COLLATE pg_catalog."default",
    tipo text COLLATE pg_catalog."default",
    estado text COLLATE pg_catalog."default",
    CONSTRAINT clientes_pkey PRIMARY KEY (id),
    CONSTRAINT unique_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS public.compras_clientes
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    id_venta bigint NOT NULL,
    id_cliente bigint NOT NULL,
    CONSTRAINT compras_clientes_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.empleados
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    nombre text COLLATE pg_catalog."default" NOT NULL,
    apellido text COLLATE pg_catalog."default" NOT NULL,
    edad integer NOT NULL,
    fecha_nac date NOT NULL,
    cedula text COLLATE pg_catalog."default" NOT NULL,
    direccion text COLLATE pg_catalog."default" NOT NULL,
    nro_tel_princ text COLLATE pg_catalog."default" NOT NULL,
    nro_tel_sec text COLLATE pg_catalog."default",
    email text COLLATE pg_catalog."default",
    cargo text COLLATE pg_catalog."default" NOT NULL,
    fecha_ingreso date NOT NULL DEFAULT CURRENT_DATE,
    CONSTRAINT empleados_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.empresa_informacion
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    ruc text COLLATE pg_catalog."default",
    razon_social text COLLATE pg_catalog."default",
    nombre_comercial text COLLATE pg_catalog."default",
    ciudad text COLLATE pg_catalog."default",
    direccion text COLLATE pg_catalog."default",
    telefonos text COLLATE pg_catalog."default",
    email text COLLATE pg_catalog."default",
    numero_establecimientos text COLLATE pg_catalog."default",
    obligado_a_contabilidad text COLLATE pg_catalog."default",
    contribuyente_regimen_rimpe text COLLATE pg_catalog."default",
    CONSTRAINT empresa_informacion_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.facturas
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    numero text COLLATE pg_catalog."default" NOT NULL,
    codigo text COLLATE pg_catalog."default" NOT NULL,
    fecha date NOT NULL,
    hora time without time zone NOT NULL,
    importe_total numeric(10, 2) NOT NULL,
    CONSTRAINT facturas_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.facturas_detalles
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    usuario_id bigint,
    fecha_emision date NOT NULL,
    estado text COLLATE pg_catalog."default" NOT NULL,
    clave_acceso text COLLATE pg_catalog."default",
    xml_firmado xml,
    numero_factura text COLLATE pg_catalog."default",
    factura_json json,
    CONSTRAINT facturas_detalles_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.metodos_pagos
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    codigo text COLLATE pg_catalog."default",
    descripcion text COLLATE pg_catalog."default",
    CONSTRAINT metodos_pagos_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.productos
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    codigo text COLLATE pg_catalog."default" NOT NULL,
    imagen text COLLATE pg_catalog."default",
    nombre text COLLATE pg_catalog."default" NOT NULL,
    estado text COLLATE pg_catalog."default" NOT NULL,
    precio_unidad numeric(8, 3) NOT NULL,
    categoria text COLLATE pg_catalog."default",
    descripcion text COLLATE pg_catalog."default",
    stock integer,
    CONSTRAINT productos_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.productos_fac
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    cod_principal text COLLATE pg_catalog."default",
    cod_auxiliar text COLLATE pg_catalog."default",
    nombre text COLLATE pg_catalog."default",
    tipo text COLLATE pg_catalog."default",
    cod_iva text COLLATE pg_catalog."default",
    im_valor_agre text COLLATE pg_catalog."default",
    ice text COLLATE pg_catalog."default",
    CONSTRAINT productos_fac_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.proveedores
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    empresa text COLLATE pg_catalog."default" NOT NULL,
    tipo_producto text COLLATE pg_catalog."default" NOT NULL,
    direccion text COLLATE pg_catalog."default" NOT NULL,
    nro_tel_princ text COLLATE pg_catalog."default" NOT NULL,
    nro_tel_sec text COLLATE pg_catalog."default",
    email text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT proveedores_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.ventas
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    id_empleado bigint NOT NULL,
    id_factura bigint NOT NULL,
    CONSTRAINT ventas_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.ventas_productos
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    id_venta bigint NOT NULL,
    id_producto bigint NOT NULL,
    cantidad integer NOT NULL,
    CONSTRAINT ventas_productos_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.compras_clientes
    ADD CONSTRAINT fk_compras_clientes_id_cliente FOREIGN KEY (id_cliente)
    REFERENCES public.clientes (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.compras_clientes
    ADD CONSTRAINT fk_compras_clientes_id_venta FOREIGN KEY (id_venta)
    REFERENCES public.ventas (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.facturas_detalles
    ADD CONSTRAINT facturas_usuario_id_fkey FOREIGN KEY (usuario_id)
    REFERENCES public.clientes (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.ventas
    ADD CONSTRAINT fk_ventas_id_empleado FOREIGN KEY (id_empleado)
    REFERENCES public.empleados (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.ventas
    ADD CONSTRAINT fk_ventas_id_factura FOREIGN KEY (id_factura)
    REFERENCES public.facturas (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.ventas_productos
    ADD CONSTRAINT fk_ventas_productos_id_producto FOREIGN KEY (id_producto)
    REFERENCES public.productos (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.ventas_productos
    ADD CONSTRAINT fk_ventas_productos_id_venta FOREIGN KEY (id_venta)
    REFERENCES public.ventas (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;

